name: Lint and Test

on:
  pull_request:
    branches: [ develop, main ]
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: install npm dependencies
        run: npm ci
      - name: run CSS linter
        run: npm run lint:css
      - name: run JS linter
        run: npm run lint:js
      - name: run unit tests
        run: npm run test:jest
      - name: run e2e tests
        env:
          NODE_ENV: ci
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        uses: cypress-io/github-action@v5
        with:
          build: npm run build:ci
          start: npm run start:ci